# Generated by Django 3.2.10 on 2021-12-20 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='data',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
