# Generated by Django 4.0 on 2021-12-20 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_alter_todo_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='data',
        ),
        migrations.AddField(
            model_name='todo',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
